### ISSUE TITLE
Missing subscription's term data in POST /saas/subscriptions/resolve response

### ISSUE THREAD

**Issue by rokf** [microsoft/commercial-marketplace-openapi#22]
Hello,

about a week ago we've noticed that the `POST /saas/subscriptions/resolve` REST API endpoint of the SaaS API has stopped returning the subscription's term data in the response body.

We're adding Azure Marketplace support to our product and the account configuration redirect suddenly began failing because of the missing data.

We're using the SaaS API's specification from this repository for HTTP client code generation.

**We've already opened a support ticked for this issue a few days ago, but we didn't get any concrete feedback yet.**

**I'm wondering if the API perhaps changed recently and the OpenAPI specification from this repository is therefore outdated?** Are we suddenly supposed to fetch the subscription's term data from somewhere else? We couldn't find any resources mentioning the deprecation of these properties. The https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2 documentation hasn't changed either.

I suppose that the API's version would be affected with such a breaking change, therefore I think that something else must've happened.

**Could you perhaps tell us if this issue is known and if it's already being worked on?** Otherwise we'll be forced to find some kind of workaround on our side.

Thank you! 🙂 

https://github.com/microsoft/commercial-marketplace-openapi/blob/ae3f6900997e0bf850dae86aec61098cf179efd3/Microsoft.Marketplace.SaaS/2018-08-31/saasapi.v2.json#L936

**Comment by rokf** [comment]
We've been told that we should fetch the term data using https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2#get-subscription after the subscription has been activated using https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2#activate-a-subscription.

The https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2#resolve-a-purchased-subscription response currently doesn't contain the term data anymore.

**We haven't been told if the previous implementation (term data is present in the resolve response) will be reverted / made available again.** If not, then the documentation - https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2 - and OpenAPI specification - https://github.com/microsoft/commercial-marketplace-openapi/blob/main/Microsoft.Marketplace.SaaS/2018-08-31/saasapi.v2.json - are both out of sync with the actual implementation.

It's also interesting that the API version hasn't changed with such a breaking change. It's still `2018-08-31`. On the other hand, everything in the `Subscription` model from the OpenAPI specification is optional, which means that one can't really tell what will be returned in a response without trying it out manually.

**Comment by OvervCW** [comment]
@rokf Our approach has been to activate the subscription, ignore the response, and then poll the *get subscription* endpoint for up to 15 seconds until the state has changed to `Subscribed` **and** there is a term start date.

**Comment by rokf** [comment]
I'm closing this issue. The OpenAPI specification has all the term fields set to optional, which means that they won't necessarily be present. There's nothing wrong with the OpenAPI specification in that regard, just with the documentation, because it's slightly misleading.
