### ISSUE TITLE
OperationActionEnum is missing Renew

### ISSUE THREAD

**Issue by pvaillant** [microsoft/commercial-marketplace-openapi#26]
Per https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-webhook there is an operation with action = "Renew" that is missing from the action enum here
https://github.com/microsoft/commercial-marketplace-openapi/blob/main/Microsoft.Marketplace.SaaS/2018-08-31/saasapi.v2.json#L1230

If the resolution is just adding the an entry for Renew, I'm happy to create a PR for this.

**Comment by santhoshb-msft** [comment]
Ack. Thanks @pvaillant , we will get this added.
