### ISSUE TITLE
Can we have support for tags to pass to publisher when customer configures it on portal during install 

### ISSUE THREAD

**Issue by priyankajayaswal1** [microsoft/commercial-marketplace-openapi#31]

**Comment by santhoshb-msft** [comment]
Hi @priyankajayaswal1 could you please help add some additional context to this request?

**Comment by santhoshb-msft** [comment]
@priyankajayaswal1 - reaching out again to see if you could add any additional context on this please? This would generally be added in the UI which implements this open api spec lib. Please feel free to correct me.
